apiVersion: apps/v1
kind: Deployment
metadata:
  name: api4
spec:
  selector:
    matchLabels:
      app: api4
  replicas: 1
  template:
    metadata:
      labels:
        app: api4
    spec:
      containers:
        - name: api4
          image: albertstarreveld/testing.graphstoreapi
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api4-service
spec:
  selector:
    app: api4
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api4-ingress-rules
  annotations:
    cert-manager.io/cluster-issuer: le-cluster-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: api4.maffe-maandag.nl
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: api4-service
            port:
              number: 80
  tls:
  - hosts:
    - api4.maffe-maandag.nl
    secretName: api4-cert