apiVersion: apps/v1
kind: Deployment
metadata:
  name: api5
spec:
  selector:
    matchLabels:
      app: api5
  replicas: 1
  template:
    metadata:
      labels:
        app: api5
    spec:
      containers:
        - name: api5
          image: albertstarreveld/testing.graphstoreapi
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: api5-service
spec:
  selector:
    app: api5
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api5-ingress-rules
  annotations:
    cert-manager.io/cluster-issuer: le-cluster-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: api5.maffe-maandag.nl
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: api5-service
            port:
              number: 80
  tls:
  - hosts:
    - api5.maffe-maandag.nl
    secretName: api5-cert