apiVersion: apps/v1
kind: Deployment
metadata:
  name: welkom
spec:
  selector:
    matchLabels:
      app: welkom
  replicas: 1
  template:
    metadata:
      labels:
        app: welkom
    spec:
      containers:
        - name: welkom
          image: maffemaandag.azurecr.io/welkom:3
          ports:
            - name: http-port
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: welkom-service
spec:
  selector:
    app: welkom
  ports:
    - name: http-port
      port: 80
      targetPort: http-port
      protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: welkom-ingress-rules
  annotations:
    cert-manager.io/cluster-issuer: le-cluster-issuer
spec:
  ingressClassName: nginx
  rules:
  - host: welkom.maffe-maandag.nl
    http:
      paths:
      - path: "/"
        pathType: Prefix
        backend:
          service:
            name: welkom-service
            port:
              number: 80
  tls:
  - hosts:
    - welkom.maffe-maandag.nl
    secretName: welkom-cert